### ISSUE TITLE
Chance to remove stale user?

### ISSUE THREAD

**Issue by yayajacky** [lfdominguez/openvpn-access-exporter#1]
Hi, this is a very cool project!

Just downloaded it and was able to compile this and get it running via a service.
I was wondering if it's possible to filter out users who hasn't been using any traffic for a months.

Just a thought, thanks!

**Comment by lfdominguez** [comment]
I will support add to prometheus the correct timestampo from OpenVPN, so you can now with the filters do that. Thanks for use

**Comment by yayajacky** [comment]
Thank you!
